# -*- coding: utf-8 -*-
"""api key

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hgqLwM240aVlJe-zE7_mu92l6zPvVtSG
"""

import os
import requests

# Retrieve the BLS API key from the environment variable (set by GitHub Actions)
BLS_API_KEY = os.getenv("BLS_API_KEY")

# Now you can use the API key in your requests
if not BLS_API_KEY:
    raise ValueError("BLS API key not found. Please add the BLS_API_KEY secret in GitHub.")